config/routes.rb
Reisebuero::Application.routes.draw do

  devise_for :users

  resources :lodgings do
    resources :bookings
  end

  resources :contacttypes

  resources :events do
    resources :event_helpers do
        get 'promote', :on => :member
        get 'demote', :on => :member
    end
  end

  resources :helper_candidates
  
  resources :users do
    resources :contacts
  end
  
  match '/my_page' => 'my_page#index'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month(/:day)))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

 root :to => 'calendar#index'

end

app/controllers/my_page_controller.rb
class MyPageController < ApplicationController
  before_filter :authenticate_user!
  def index
    @month_now = (Time.zone || Time).now.month.to_i
    @year_now = (Time.zone || Time).now.year.to_i
    if @month_now >1 then
      @last_month_start = Date.new(@year_now, @month_now-1).to_time
    else
      @last_month_start = Date.new(@year_now-1, 12).to_time
    end
    
    @user = current_user
    @contacts = @user.contacts
#    @event_helpers = EventHelper.find_all_by_user_id(@user.id)
    @event_helpers = EventHelper.joins(:event).where("end_at >= :month_start OR start_at >= :month_start", {:month_start => @last_month_start}).find_all_by_user_id(@user.id)
    @lodgings = Lodging.find_all_by_user_id_and_request(@user.id, false)
    @lodging_requests = Lodging.find_all_by_user_id_and_request(@user.id, true)
    @helper_candidates = @user.helper_candidates
  end
end

app/helpers/my_page_helper.rb
module MyPageHelper
end

app/views/my_page/index.html.erb
<div class="row">
  <div class="span6">
    <div id="events">
      <h3>
        <%= t('events') %>
      </h3>
      <ul class="unstyled">
        <% @event_helpers.each do |event_helper| %>
          <%= render :partial => 'events/event', :locals => {:event => event_helper.event} %>
        <% end %>
      </ul>
      <%= button_new(new_event_path) %>
    </div>
    
    <div id="helper_candidates">
      <h3>
        <%= t('helper_candidates') %>
      </h3>
      <ul class="unstyled">
        <%= render @helper_candidates %>
      </ul>
      <%= button_new(new_helper_candidate_path) %>
    </div>

    <div id="lodgings">
      <h3><%= t('lodgings') %></h3>
      <ul class="unstyled">
        <%= render :partial => 'lodgings/lodging_event', :collection => @lodgings %>
      </ul>
      <%= button_new(new_lodging_path(:request => false)) %>
    </div>

    <div id="lodging_requests">
      <h3><%= t('lodging_requests') %></h3>
      <ul class="unstyled">
        <%= render :partial => 'lodgings/lodging_event', :collection => @lodging_requests %>
      </ul>
      <%= button_new(new_lodging_path(:request => true)) %>
    </div>
  </div>
  <div class="span6">
    <div id="user">
      <h3>
        <%= t('user') %>
      </h3>
      <%= @user.username %> <br/>
      <%= @user.email %> <br/>
      <%= button_edit(edit_user_registration_path, 'btn btn-mini', t('change_registration')) %>
    </div>

    <div id="contacts">
      <h3>
        <%= t('contact') %>
      </h3>
      <% unless @contacts.any? %>
        <p class="text-error"><%= t('please_add_contacts') %></p>
      <% end %>
      <%= render :partial => 'contacts/contact', :collection => @contacts %>
    <p>
      <%= button_new(new_user_contact_path(@user)) %>
    </p>
    </div>
  </div>
</div>