config/routes.rb
Reisebuero::Application.routes.draw do

  devise_for :users

  resources :lodgings do
    resources :bookings
  end

  resources :contacttypes

  resources :events do
    resources :event_helpers do
        get 'promote', :on => :member
        get 'demote', :on => :member
    end
  end

  resources :helper_candidates
  
  resources :users do
    resources :contacts
  end
  
  match '/my_page' => 'my_page#index'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month(/:day)))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

 root :to => 'calendar#index'

end

app/views/shared/_login.html.erb
<% if user_signed_in? %>
  <%= link_to current_user.username, :controller => '/my_page', :action => "index" %>
  <%= link_to t('sign_out'), destroy_user_session_path %>
<% else %>
  <%= (link_to t('sign_up'), new_user_registration_path) + ' ' + t('or') + ' ' + (link_to t('sign_in') ,new_user_session_path) %>
<% end %>

app/views/shared/_menu.html.erb
<ul class="nav">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t('pages') %>
      <b class="caret"></b>
      <%= render 'shared/pages_menu' %>
    </a>
  </li>
        <li>
          <%= link_to t('my_page'), :controller => '/my_page', :action => 'index' unless current_user.nil? %>
        </li>
	<li><%= link_to t('calendar'), calendar_path %></li>
	<li><%= link_to t('events'), events_path %></li>
        <li>
          <%= link_to t('helper_candidates'), helper_candidates_path if can? :manage, HelperCandidate %>
        </li>
        <li>
          <%= link_to t('lodgings'), lodgings_path if can? :manage, Lodging %>
        </li>
	<li><%= link_to t('users'), users_path if can? :manage, User %></li>
</ul>
	

app/views/shared/_pages_menu.erb
<ul class="dropdown-menu">
  <li><%= link_to t('about'), page_path(t('page_about')) %></li>
  <li>
    <%= link_to t('help'), page_path(t('page_help')) %>
  </li>
  <li><%= link_to t('imprint'), page_path(t('page_imprint'))  %> </li>
</ul>