config/routes.rb
Reisebuero::Application.routes.draw do

  devise_for :users

  resources :lodgings do
    resources :bookings
  end

  resources :contacttypes

  resources :events do
    resources :event_helpers do
        get 'promote', :on => :member
        get 'demote', :on => :member
    end
  end

  resources :helper_candidates
  
  resources :users do
    resources :contacts
  end
  
  match '/my_page' => 'my_page#index'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month(/:day)))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

 root :to => 'calendar#index'

end

app/models/event.rb
class Event < ActiveRecord::Base     
  has_event_calendar
  geocoded_by :location
  attr_accessible :all_day, :description, :end_at, :location, :name, :start_at, :uid, :latitude, :longitude
  has_many :event_categories, :dependent => :destroy
  has_many :categories, :through => :event_categories
  has_many :event_helpers, :dependent => :destroy
  has_many :lodgings, :dependent => :destroy
  
  validates :name, :start_at, :end_at, :presence => true
	validates :uid, :uniqueness => true
  
  after_validation :geocode, :if => :location_changed?
	
	before_create do |event|
		event.uid = UUIDTools::UUID.random_create.to_s
	end
end

app/models/event_helper.rb
class EventHelper < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  belongs_to :category
  attr_accessible :category
  
  validates :user_id, :uniqueness => { :scope => :event_id, :message => I18n.t('user_already_helper')}, :unless => Proc.new { |e| e.user_id.nil? or e.event_id.nil? }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
#  before_filter :orga_filter, :except => [:show,:index,:new,:create]
  load_and_authorize_resource
  
  # GET /events
  # GET /events.json
  def index
    @month_now = (Time.zone || Time).now.month.to_i
    @year_now = (Time.zone || Time).now.year.to_i
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i
    @day = params[:day].to_i || 0
    if @month_now >1 then
      @last_month_start = Date.new(@year_now, @month_now-1).to_time
    else
      @last_month_start = Date.new(@year_now-1, 12).to_time
    end
    @month_start = Date.new(@year, @month).to_time
    if @month < 12 then
      @month_end = Date.new(@year, @month+1).to_time
    else
      @month_end = Date.new(@year+1, 1).to_time
    end
    if @day > 0 then
      @day_start = Date.new(@year, @month, @day).to_time
      @day_end = Date.new(@year, @month, @day+1).to_time
      @shown_day = Date.civil(@year, @month, @day)
    end
    @next_year_end = Date.new(@year_now+2, 1).to_time

    @shown_month = Date.civil(@year, @month)

    if @day > 0 then
      @events_day = Event.where("end_at BETWEEN :day_start AND :day_end OR start_at BETWEEN :day_start AND :day_end", {:day_start => @day_start, :day_end => @day_end})
    else
      @events = Event.where("end_at BETWEEN :month_start AND :month_end OR start_at BETWEEN :month_start AND :month_end", {:month_start => @month_start, :month_end => @month_end})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
	  	format.ics do
				send_data(	export_ical_range(@last_month_start,@next_year_end).export,
										:filename=>"reisebuero_events.ics",
										:disposition=>"inline; filename=reisebuero_events.ics",
										:type=>"text/calendar")
			end
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @helpers = @event.event_helpers.find_all_by_orga(false,nil)
    @orgas = @event.event_helpers.find_all_by_orga(true)
#    @user_is_orga = orga?
    @user_is_helper = EventHelper.where(:event_id => @event , :user_id => current_user).exists?
    @lodgings = @event.lodgings.find_all_by_request(false,nil)
    @lodging_requests = @event.lodgings.find_all_by_request(true)
    @contacts = Contact.find_all_by_user_id_and_public(@orgas.first.user_id, true)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
	  	format.ics do
				send_data(	export_ical(@event).export,
										:filename=>"reisebuero_event.ics",
										:disposition=>"inline; filename=reisebuero_event.ics",
										:type=>"text/calendar")
			end
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
		@event_helper = @event.event_helpers.build
    @event_helper.user = current_user   # current_user not available in model
    @event_helper.orga = true
    @event_helper.save

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

	def export_ical_range(start_date, end_date)
		ical = RiCal.Calendar do
			events = Event.where("end_at BETWEEN :month_start AND :month_end OR start_at BETWEEN :month_start AND :month_end", {:month_start => start_date, :month_end => end_date})
			events.each do |the_event|
        event do
          summary the_event.name
          uid the_event.uid
          description the_event.description
          dtstart the_event.start_at.to_datetime
          dtend the_event.end_at.to_datetime
          location the_event.location
          the_event.event_helpers.each do |event_helper|
            add_attendee event_helper.user.username
          end
        end
			end
		end
	end
  
  def export_ical(event)
		ical = RiCal.Calendar do
      event do
        summary event.name
        uid event.uid
        description event.description
        dtstart event.start_at.to_datetime
        dtend event.end_at.to_datetime
        location event.location
        event.event_helpers.each do |event_helper|
          add_attendee event_helper.user.username
        end
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<li>
  <span class="event_name">
    <%= link_to event.name, event %>
  </span>
  <span class="event_orga">
    <% if not event.event_helpers.find_by_user_id(current_user.id).nil? and event.event_helpers.find_by_user_id(current_user.id).orga? %>
    (<%= t('event_orga') %>)
    <% else  %>
    (<%= t('event_helper') %>)
    <% end %>
  </span><br/>
  <%= raw  display_time_event(event) %><br/>
</li>

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :start_at, :input_html => {:class => 'input-small'} %>
  <%= f.input :end_at, :input_html => {:class => 'input-small'} %>
  <%= f.input :location, :input_html => {:rows => '5', :class => 'input-xxlarge'} %>
  <%= f.input :description, :input_html => {:rows => '5', :class => 'input-xxlarge'} %>
  <%= f.input :all_day %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>

<% end %>

app/views/events/_list.html.erb
<li>
	<%= link_to event.name, event %>, 
	<%= raw(display_time_event(event)) %> 
        <%= button_edit(edit_event_path(event)) if can? :update, event %>
        <%= button_destroy(event_path(event)) if can? :destroy, event %>
</li>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<div class="row">
  <div class="span3">
    <ul class="pager"><li class="previous"><%= prev_month_link(@shown_month.prev_month) %></li></ul>
  </div>
  <div class="span6">
    <center>
      <% if @day > 0 then %>
        <h3><%= raw(I18n.localize(@shown_day, :format => "%A, %d.%m.%Y")) %></h3>
      <% else %>
        <h3><%= raw(I18n.localize(@shown_month, :format => "%B %Y")) %></h3>
      <% end %>
  </center>
  </div>
  <div class="span3">
    <ul class="pager"><li class="next"> <%=  next_month_link(@shown_month.next_month) %></li></ul>
  </div>
</div>

<% if @day > 0 then %>
  <ul>
    <%= render :partial => "list", :collection => @events_day, :as => :event %>
  </ul>
<% else %>
  <ul>
    <%= render :partial => "list", :collection => @events, :as => :event %>
  </ul>
<% end %>

<%= link_to t('new_event', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' if can? :create, Event %>
<%= link_to t('ical_export_default'),
            event_path(:format => :ics),
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class="row">
  <div class="span6">
    <h2>
      <%= @event.name %>
      <%= button_edit(edit_event_path(@event)) if can? :edit, @event %>
      <%= button_destroy(event_path(@event)) if can? :destroy, @event %>
    </h2>
    <p>
            <%= raw(display_time_event(@event)) %> 
            <% if @event.all_day %>
              (<%=t('all_day')%>)
            <% end %>
    </p>

    <p>
      <b><%=t('location')%>:</b>
      <%= simple_format(@event.location) %>
        <a class="accordion-toggle" data-toggle="collapse" href="#collapseOne">
          <i class="icon-chevron-down"></i> <small><%= t('coordinates') %></small>
        </a>
    </p>

      <div id="collapseOne" class="accordion-body collapse">
          <p>
            <small>
              <%= link_to "http://www.openstreetmap.de/karte.html?zoom=15&lat=#{@event.latitude}&lon=#{@event.longitude}&layers=B000" do %>
                (<%= @event.longitude %>,
                <%= @event.latitude %>)
              <% end %>
            </small>
          </p>
      </div>

    <p>
      <b><%=t('description')%>:</b>
      <%= simple_format(@event.description) %>
    </p>

    <% if can? :read, EventHelper %>
    <div id="event_orgas">
      <h3><%= t('event_orgas') %></h3>
      <ul>
        <%= render :partial => 'event_helpers/event_helper', :collection => @orgas, :locals => { :user_is_orga => @user_is_orga} %>
      </ul>
    </div>

    <div id="event_helpers">
      <h3><%= t('event_helpers') %></h3>
      <ul>
        <%= render :partial => 'event_helpers/event_helper', :collection => @helpers, :locals => { :user_is_orga => @user_is_orga} %>
      </ul>
      <% if can? :create, EventHelper and not @user_is_helper %>
        <%= form_for([@event, @event.event_helpers.build]) do |helper_form| %>
          <div class="action">
            <%= helper_form.submit t('helper_submit') %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
    <div class="span6">
    <h2>
      <%= t('contact') %>
    </h2>
    <% if @orgas.first.user == current_user and not @contacts.any? %>
      <p class="text-error"><%= t('please_add_contacts') %></p>
    <% end %>
     <%= render :partial => 'contacts/contact', :collection => @contacts %>
    <% if @orgas.first.user == current_user %>
    <p>
      <%= button_new(new_user_contact_path(@current_user)) %>
    </p>
    <% end %>
    </div>
  
</div>

<% end %>

<div class="row">
  <% if can? :read, Lodging %>

  <div id="lodgings" class="span6">
    <h3><%= t('lodgings') %></h3>
    <ul>
      <%= render :partial => 'lodgings/lodging', :collection => @lodgings %>
    </ul>
    <p>
      <%= button_new(new_lodging_path(:event => @event.id, :request => false, :start_at => @event.start_at, :end_at => @event.end_at), 'btn btn-mini btn-primary', t('new_lodging')) %>
    </p>
  </div>

  <div id="lodging_requests" class="span6">
    <h3><%= t('lodging_requests') %></h3>
    <ul>
      <%= render :partial => 'lodgings/lodging', :collection => @lodging_requests %>
    </ul>
    <p>
      <%= button_new(new_lodging_path(:event => @event.id, :request => true, :start_at => @event.start_at, :end_at => @event.end_at), 'btn btn-mini btn-primary', t('new_lodging_request')) %>
    </p>
  </div>
</div>
<% end %>