config/routes.rb
Reisebuero::Application.routes.draw do

  devise_for :users

  resources :lodgings do
    resources :bookings
  end

  resources :contacttypes

  resources :events do
    resources :event_helpers do
        get 'promote', :on => :member
        get 'demote', :on => :member
    end
  end

  resources :helper_candidates
  
  resources :users do
    resources :contacts
  end
  
  match '/my_page' => 'my_page#index'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month(/:day)))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

 root :to => 'calendar#index'

end

app/controllers/event_helpers_controller.rb
class EventHelpersController < ApplicationController
#  before_filter :authenticate_user!, :except => [:show, :index]
#  before_filter :orga_filter, :only => [:promote, :demote]
  #before_filter :self_filter, :except => [:show, :index, :promote, :create, :new]
  before_filter :keep_last_orga, :only => [:demote, :destroy]
  load_and_authorize_resource
  # GET /event_helpers
  # GET /event_helpers.json
  def index
    @event_helpers = EventHelper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_helpers }
    end
  end

  # GET /event_helpers/1
  # GET /event_helpers/1.json
  def show
    @event_helper = EventHelper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_helper }
    end
  end

  # GET /event_helpers/new
  # GET /event_helpers/new.json
  def new
    @event_helper = EventHelper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_helper }
    end
  end

  # GET /event_helpers/1/edit
  def edit
    @event_helper = EventHelper.find(params[:id])
  end

  # POST /event_helpers
  # POST /event_helpers.json
  def create
    @event = Event.find(params[:event_id])
    @event_helper = @event.event_helpers.create(params[:event_helper])
    @event_helper.user = current_user
    if @event_helper.valid?
      @event_helper.save
    else
      flash[:error] = t('user_already_helper')
      @event_helper.destroy
    end
    redirect_to event_path(@event)

#    respond_to do |format|
#      if @event_helper.save
#        format.html { redirect_to @event_helper, notice: 'Event helper was successfully created.' }
#        format.json { render json: @event_helper, status: :created, location: @event_helper }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @event_helper.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PUT /event_helpers/1
  # PUT /event_helpers/1.json
  def update
    @event_helper = EventHelper.find(params[:id])

    respond_to do |format|
      if @event_helper.update_attributes(params[:event_helper])
        format.html { redirect_to @event_helper, notice: 'Event helper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_helpers/1
  # DELETE /event_helpers/1.json
  def destroy
    @event_helper = EventHelper.find(params[:id])
    @event_helper.destroy

    respond_to do |format|
      format.html { redirect_to event_url(@event_helper.event) }
      format.json { head :no_content }
    end
  end
  
  def promote
     @event_helper = EventHelper.find(params[:id])
     authorize! :promote, @event_helper
     @event_helper.orga = true
     @event_helper.save
     redirect_to event_path(@event_helper.event)
 end

 def demote
     @event_helper = EventHelper.find(params[:id])
     @event_helper.orga = false
     @event_helper.save
     redirect_to event_path(@event_helper.event)
 end
#
#  def self_filter
#    @event_helper = EventHelper.find(params[:id])
#    unless @event_helper.user_id = current_user.id
#      flash[:error] = t('cannot_edit_other_event_helper')
#      redirect_to event_url(@event_helper.event)
#    end
#  end
  
  def keep_last_orga
    @event_helper = EventHelper.find(params[:id])
    unless @event_helper.orga == false || EventHelper.where(:event_id => @event_helper.event, :orga => true).count() > 1
      flash[:error] = t('must_have_orga')
      redirect_to event_url(@event_helper.event)
    end
  end
end

app/helpers/event_helpers_helper.rb
module EventHelpersHelper
end

app/views/event_helpers/_event_helper.erb
<li>
  <% if event_helper.user %>
    <%= event_helper.user.username %>
  <% end %>
</li>

app/views/event_helpers/_event_helper.html.erb
<% if event_helper.user %>
  <li>
    <% if can? :show, event_helper.user %>
      <%= link_to event_helper.user.username, event_helper.user %>
    <% else %>
      <%= event_helper.user.username %>
    <% end %>
    <%= button(promote_event_event_helper_path(event_helper.event, event_helper), 'btn btn-mini', t('promote_helper'), 'chevron-up') if can? :promote, event_helper and not event_helper.orga? %>
    <%= button(demote_event_event_helper_path(event_helper.event, event_helper), 'btn btn-mini', t('demote_orga'), 'chevron-down') if can? :demote, event_helper and event_helper.orga? %>
    <%= button_destroy(event_event_helper_path(event_helper.event, event_helper)) if can? :destroy, event_helper %>
  </li>
<% end %>

app/views/event_helpers/_form.html.erb
<%= form_for(@event_helper) do |f| %>
  <% if @event_helper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_helper.errors.count, "error") %> prohibited this event_helper from being saved:</h2>

      <ul>
      <% @event_helper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_helpers/edit.html.erb
<h1>Editing event_helper</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_helper %> |
<%= link_to 'Back', event_helpers_path %>

app/views/event_helpers/index.html.erb
<h1>Listing event_helpers</h1>

<table>
  <tr>
    <th>Event</th>
    <th>User</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_helpers.each do |event_helper| %>
  <tr>
    <td><%= event_helper.event %></td>
    <td><%= event_helper.user %></td>
    <td><%= event_helper.category %></td>
    <td><%= link_to 'Show', event_helper %></td>
    <td><%= link_to 'Edit', edit_event_helper_path(event_helper) %></td>
    <td><%= link_to 'Destroy', event_helper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event helper', new_event_helper_path %>

app/views/event_helpers/new.html.erb
<h1>New event_helper</h1>

<%= render 'form' %>

<%= link_to 'Back', event_helpers_path %>

app/views/event_helpers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event_helper.event %>
</p>

<p>
  <b>User:</b>
  <%= @event_helper.user %>
</p>

<p>
  <b>Category:</b>
  <%= @event_helper.category %>
</p>


<%= link_to 'Edit', edit_event_helper_path(@event_helper) %> |
<%= link_to 'Back', event_helpers_path %>